[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  no_match_test = 'testFork_|testForkFuzz_|testTotalAssetsLtVaultAssetsBalance|testTotalAssetsLtTotalSupply|testTotalAssetsGtVaultAssetsBalance|testTotalAssetsGtTotalSupply|testConvertToSharesIntOverflowLimitFollowsSolmate|testConvertToAssetsIntOverflowLimitFollowsSolmate|testDepositSupportsEIP20ApproveTransferFromAssets|testMintSupportsEIP20ApproveTransferFromAssets|testDealIntendedSharesToDummyUsers|testNoDiscrepancyConvertToAssetsAndPreviewMint|testNoDiscrepancyConvertToSharesAndPreviewWithdraw'
  no_match_contract = 'AaveStrategyVaultForkTest|SizeMetaVaultForkTest'
  solc_version = '0.8.23'
  evm_version = 'shanghai'
  ignored_warnings_from = ["lib"]
  optimizer = true
  optimizer_runs = 200
  via_ir = false

[profile.fork]
  src = "src"
  out = "out"
  libs = ["lib"]
  match_test = 'testFork_|testForkFuzz_'
  solc_version = '0.8.23'
  evm_version = 'shanghai'
  ignored_warnings_from = ["lib"]
  optimizer = true
  optimizer_runs = 200
  via_ir = false

[rpc_endpoints]
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
